/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stockp1;

import java.awt.print.PrinterException;
import javax.swing.table.TableModel;

/**
 *
 * @author Sarvadnya
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form payinvoice
     */
    
    String ltotal;
    public print(String total, TableModel model) throws PrinterException {
        initComponents();
        
        this.ltotal = total;
        
        txtprint.setText(txtprint.getText()+"************************************************ \n");
        txtprint.setText(txtprint.getText()+"********INVENTORY MANAGEMENT SYSTEM************* \n");
        txtprint.setText(txtprint.getText()+"*************BILL GENERATION******************\n");
        txtprint.setText(txtprint.getText()+"Product" + "\t" + "Quantity" + "\t" + "Price" + "\t" + "Total" + "\n");
        
        for(int i = 0; i<model.getRowCount(); i++){
            String product = (String) model.getValueAt(i, 1);
             String Quantity = (String) model.getValueAt(i, 2);
              String price = (String) model.getValueAt(i, 3);
               String dtotal = (String) model.getValueAt(i, 4);
               txtprint.setText(txtprint.getText()+product + "\t" + Quantity + "\t" + price + "\t" + total + "\n");
        }
        

        txtprint.setText(txtprint.getText()+"\n");
        txtprint.setText(txtprint.getText()+"\n");
         txtprint.setText(txtprint.getText()+"                      " + "SubTotal : " + total +     "\n");
        txtprint.setText(txtprint.getText()+"********INVENTORY MANAGEMENT SYSTEM*******\n");  
        txtprint.setText(txtprint.getText()+"******************************************\n");
        txtprint.setText(txtprint.getText()+"*****************THANK YOU***************\n");
        txtprint.setText(txtprint.getText()+"*****************VISIT AGAIN ************\n");
        
        txtprint.print();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new print(total, jTable1.getModel()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
